### ISSUE TITLE
Kompilierung schlägt fehl

### ISSUE THREAD

**Issue by brezel64** [DrNeuroSurg/WT32#1]
Arduino: 1.8.13 (Linux), Board: "ESP32S3 Dev Module, Disabled, Disabled, QIO 80MHz, 8MB (64Mb), Core 1, Core 1, Hardware CDC and JTAG, Enabled, Disabled, Disabled, UART0 / Hardware CDC, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi), 921600, None, Disabled"

In file included from /home/pi/Arduino/WT32/HelloWorld/HelloWorld/HelloWorld.ino:2:
wt32_sc01_plus.h:150:8: error: 'lv_disp_draw_buf_t' does not name a type; did you mean 'lv_draw_buf_t'?
 static lv_disp_draw_buf_t draw_buf;
        ^~~~~~~~~~~~~~~~~~
        lv_draw_buf_t
wt32_sc01_plus.h:151:8: error: 'lv_disp_drv_t' does not name a type; did you mean 'lv_fs_drv_t'?
 static lv_disp_drv_t disp_drv;
        ^~~~~~~~~~~~~
        lv_fs_drv_t
wt32_sc01_plus.h:157:20: error: variable or field 'my_disp_flush' declared void
 void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
                    ^~~~~~~~~~~~~
wt32_sc01_plus.h:157:20: error: 'lv_disp_drv_t' was not declared in this scope
sketch/wt32_sc01_plus.h:157:20: note: suggested alternative: 'lv_fs_drv_t'
 void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
                    ^~~~~~~~~~~~~
                    lv_fs_drv_t
wt32_sc01_plus.h:157:35: error: 'disp' was not declared in this scope
 void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
                                   ^~~~
sketch/wt32_sc01_plus.h:157:35: note: suggested alternative: 'dup'
 void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
                                   ^~~~
                                   dup
wt32_sc01_plus.h:157:41: error: expected primary-expression before 'const'
 void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
                                         ^~~~~
wt32_sc01_plus.h:157:75: error: expected primary-expression before '*' token
 void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
                                                                           ^
wt32_sc01_plus.h:157:76: error: 'color_p' was not declared in this scope
 void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
                                                                            ^~~~~~~
sketch/wt32_sc01_plus.h:157:76: note: suggested alternative: 'lv_color_t'
 void my_disp_flush(lv_disp_drv_t *disp, const lv_area_t *area, lv_color_t *color_p)
                                                                            ^~~~~~~
                                                                            lv_color_t
wt32_sc01_plus.h:170:23: error: variable or field 'my_touchpad_read' declared void
 void my_touchpad_read(lv_indev_drv_t *indev_driver, lv_indev_data_t *data)
                       ^~~~~~~~~~~~~~
wt32_sc01_plus.h:170:23: error: 'lv_indev_drv_t' was not declared in this scope
sketch/wt32_sc01_plus.h:170:23: note: suggested alternative: 'lv_indev_data_t'
 void my_touchpad_read(lv_indev_drv_t *indev_driver, lv_indev_data_t *data)
                       ^~~~~~~~~~~~~~
                       lv_indev_data_t
wt32_sc01_plus.h:170:39: error: 'indev_driver' was not declared in this scope
 void my_touchpad_read(lv_indev_drv_t *indev_driver, lv_indev_data_t *data)
                                       ^~~~~~~~~~~~
sketch/wt32_sc01_plus.h:170:39: note: suggested alternative: 'lv_indev_reset'
 void my_touchpad_read(lv_indev_drv_t *indev_driver, lv_indev_data_t *data)
                                       ^~~~~~~~~~~~
                                       lv_indev_reset
wt32_sc01_plus.h:170:69: error: expected primary-expression before '*' token
 void my_touchpad_read(lv_indev_drv_t *indev_driver, lv_indev_data_t *data)
                                                                     ^
wt32_sc01_plus.h:170:70: error: 'data' was not declared in this scope
 void my_touchpad_read(lv_indev_drv_t *indev_driver, lv_indev_data_t *data)
                                                                      ^~~~
sketch/wt32_sc01_plus.h:170:70: note: suggested alternative: 'atan'
 void my_touchpad_read(lv_indev_drv_t *indev_driver, lv_indev_data_t *data)
                                                                      ^~~~
                                                                      atan
sketch/wt32_sc01_plus.h: In function 'bool init_Display()':
wt32_sc01_plus.h:205:28: error: 'draw_buf' was not declared in this scope
     lv_disp_draw_buf_init(&draw_buf, disp_draw_buf, disp_draw_buf2, screenWidth * SCR);
                            ^~~~~~~~
sketch/wt32_sc01_plus.h:205:28: note: suggested alternative: 'disp_draw_buf'
     lv_disp_draw_buf_init(&draw_buf, disp_draw_buf, disp_draw_buf2, screenWidth * SCR);
                            ^~~~~~~~
                            disp_draw_buf
wt32_sc01_plus.h:205:5: error: 'lv_disp_draw_buf_init' was not declared in this scope
     lv_disp_draw_buf_init(&draw_buf, disp_draw_buf, disp_draw_buf2, screenWidth * SCR);
     ^~~~~~~~~~~~~~~~~~~~~
sketch/wt32_sc01_plus.h:205:5: note: suggested alternative: 'lv_draw_buf_init'
     lv_disp_draw_buf_init(&draw_buf, disp_draw_buf, disp_draw_buf2, screenWidth * SCR);
     ^~~~~~~~~~~~~~~~~~~~~
     lv_draw_buf_init
wt32_sc01_plus.h:208:23: error: 'disp_drv' was not declared in this scope
     lv_disp_drv_init(&disp_drv);
                       ^~~~~~~~
wt32_sc01_plus.h:208:5: error: 'lv_disp_drv_init' was not declared in this scope
     lv_disp_drv_init(&disp_drv);
     ^~~~~~~~~~~~~~~~
sketch/wt32_sc01_plus.h:208:5: note: suggested alternative: 'lv_fs_drv_init'
     lv_disp_drv_init(&disp_drv);
     ^~~~~~~~~~~~~~~~
     lv_fs_drv_init
wt32_sc01_plus.h:212:25: error: 'my_disp_flush' was not declared in this scope
     disp_drv.flush_cb = my_disp_flush;
                         ^~~~~~~~~~~~~
wt32_sc01_plus.h:214:5: error: 'lv_disp_drv_register' was not declared in this scope
     lv_disp_drv_register(&disp_drv);
     ^~~~~~~~~~~~~~~~~~~~
sketch/wt32_sc01_plus.h:214:5: note: suggested alternative: 'lv_fs_drv_register'
     lv_disp_drv_register(&disp_drv);
     ^~~~~~~~~~~~~~~~~~~~
     lv_fs_drv_register
wt32_sc01_plus.h:217:12: error: 'lv_indev_drv_t' does not name a type; did you mean 'lv_indev_data_t'?
     static lv_indev_drv_t indev_drv;
            ^~~~~~~~~~~~~~
            lv_indev_data_t
wt32_sc01_plus.h:218:24: error: 'indev_drv' was not declared in this scope
     lv_indev_drv_init(&indev_drv);
                        ^~~~~~~~~
wt32_sc01_plus.h:218:5: error: 'lv_indev_drv_init' was not declared in this scope
     lv_indev_drv_init(&indev_drv);
     ^~~~~~~~~~~~~~~~~
sketch/wt32_sc01_plus.h:218:5: note: suggested alternative: 'lv_fs_drv_init'
     lv_indev_drv_init(&indev_drv);
     ^~~~~~~~~~~~~~~~~
     lv_fs_drv_init
wt32_sc01_plus.h:220:25: error: 'my_touchpad_read' was not declared in this scope
     indev_drv.read_cb = my_touchpad_read;
                         ^~~~~~~~~~~~~~~~
sketch/wt32_sc01_plus.h:220:25: note: suggested alternative: 'touchRead'
     indev_drv.read_cb = my_touchpad_read;
                         ^~~~~~~~~~~~~~~~
                         touchRead
wt32_sc01_plus.h:221:5: error: 'lv_indev_drv_register' was not declared in this scope
     lv_indev_drv_register(&indev_drv);
     ^~~~~~~~~~~~~~~~~~~~~
sketch/wt32_sc01_plus.h:221:5: note: suggested alternative: 'lv_fs_drv_register'
     lv_indev_drv_register(&indev_drv);
     ^~~~~~~~~~~~~~~~~~~~~
     lv_fs_drv_register
exit status 1
'lv_disp_draw_buf_t' does not name a type; did you mean 'lv_draw_buf_t'?

**Comment by DrNeuroSurg** [comment]
Hallo,
die Ursache - sieht jedenfalls ganz danach aus - ist, dass die Beispiele in diesem Repository mit LVGL Version 8.xxx erstellt wurden - du benutzt **sehr** wahrscheinlich Version 9. 

Es gibt 2 Möglichkeiten:

- "Downgrade", d.h. im Arduino-Library-Manager LVGL deinstallieren und dann eine "alte" Version installieren oder
- mein neues Repository benutzen:  https://github.com/DrNeuroSurg/WT32-SC01-PLUS, da gibts auch Beispiele -bitte unbedingt die in dem neuen Repository vorhandene **lv_conf.h** kopieren !!!

**Comment by brezel64** [comment]
Hallo,

vielen Dank, mit lvgl 8.3.5 funktioniert es.
